version: "2"

linters:
  default: none
  enable:
    - govet
    - revive
    - ineffassign
    - staticcheck  # replaces gosimple in v2
    - unparam
    - unused
    - misspell
  settings:
    misspell:
      locale: US
  exclusions:
    rules:
      - path: '(.+)\.go$'
        text: 'should have a package comment'
      - path: '(.+)\.go$'
        text: 'error strings should not be capitalized or end with punctuation or a newline'
      - path: '(.+)\.go$'
        text: 'should have comment'  # TODO(aead): Remove once all exported ident. have comments!

formatters:
  enable:
    - goimports
